import type { DataSource, IntelligenceItem, Deal, Event, Clause, MarketSnapshot, NewsItem } from "./types";
import { ItemType, Priority } from "./types";

export const MOCK_ITEMS: IntelligenceItem[] = [
  {
    id: "1",
    type: ItemType.LITIGATION,
    title: "Motion to Dismiss - FTC v. Microsoft",
    source: "CourtListener",
    timestamp: "2023-10-12T09:42:12Z",
    priority: Priority.CRITICAL,
    ticker: "MSFT",
    content:
      "UNITED STATES DISTRICT COURT\nNORTHERN DISTRICT OF CALIFORNIA\n\nFEDERAL TRADE COMMISSION, Plaintiff,\n v.\nMICROSOFT CORP. and ACTIVISION BLIZZARD, INC., Defendants.\n\nCASE NO. 3:23-cv-02880-JSC\n\nDEFENDANT MICROSOFT CORP.'S MOTION TO DISMISS\n\nDefendant Microsoft Corp. (\"Microsoft\") respectfully moves to dismiss the complaint filed by the Federal Trade Commission (\"FTC\") pursuant to Federal Rule of Civil Procedure 12(b)(6). The FTC's attempt to block Microsoft's acquisition of Activision Blizzard, Inc. fails to state a claim upon which relief can be granted because it relies on a speculative theory of harm that contradicts the vertical merger guidelines and ignores the fiercely competitive nature of the gaming industry.\n\nMicrosoft argues that the FTC has failed to allege a plausible relevant market and has not demonstrated a likelihood of substantial competitive harm. Furthermore, Microsoft has entered into binding 10-year commitments to keep Call of Duty available on competitor platforms, negating the central premise of the FTC's foreclosure theory.",
    tags: ["Antitrust", "Merger", "Acquisition"],
    metadata: {
      caseNumber: "3:23-cv-02880-JSC",
      court: "N.D. Cal.",
    },
  },
  {
    id: "2",
    type: ItemType.SEC_FILING,
    title: "8-K: Entry into Material Definitive Agreement",
    source: "SEC EDGAR",
    timestamp: "2023-10-12T08:30:00Z",
    priority: Priority.HIGH,
    ticker: "ADBE",
    content:
      "Item 1.01 Entry into a Material Definitive Agreement.\n\nOn October 12, 2023, Adobe Inc. (\"Adobe\") entered into an Agreement and Plan of Merger (the \"Merger Agreement\") with Figma, Inc. (\"Figma\"). Pursuant to the Merger Agreement, Adobe will acquire Figma for approximately $20 billion in cash and stock.\n\nThe Merger Agreement contains customary representations, warranties, and covenants. The transaction is subject to regulatory approvals and customary closing conditions. In the event the merger is terminated under certain circumstances involving antitrust hurdles, Adobe may be required to pay a reverse termination fee of $1 billion.",
    tags: ["M&A", "Software", "Reg-FD"],
    metadata: {
      filingType: "8-K",
    },
  },
  {
    id: "3",
    type: ItemType.NEWS,
    title: "Qualcomm Rumored to Explore Takeover of Intel",
    source: "Wall Street Journal",
    timestamp: "2023-10-12T10:15:00Z",
    priority: Priority.MEDIUM,
    ticker: "INTC",
    content:
      "Qualcomm Inc. has approached Intel Corp. about a potential takeover of the struggling chip maker, according to people familiar with the matter. A deal, if it happens, would be one of the largest technology mergers in history.\n\nThe talks come as Intel faces mounting losses in its foundry business and a declining share price. A combination with Qualcomm, the dominant supplier of mobile phone chips, could reshape the semiconductor landscape, though it would likely face intense regulatory scrutiny globally.",
    tags: ["Rumor", "Semiconductor", "Hostile"],
    metadata: {},
  },
  {
    id: "4",
    type: ItemType.PREDICTION,
    title: "Kroger / Albertsons Merger Approval Odds",
    source: "Polymarket",
    timestamp: "2023-10-12T11:00:00Z",
    priority: Priority.HIGH,
    ticker: "KR",
    content:
      "Market: Will the Kroger-Albertsons merger be completed by June 30, 2024?\n\nCurrent Probability: 32%\nVolume: $4.2M\n\nAnalysis: The market sentiment has trended downward following recent comments from the FTC Chair regarding consolidation in the grocery sector. Traders are pricing in a significant risk of litigation to block the deal.",
    tags: ["Arbitrage", "Antitrust"],
    metadata: {
      probability: 0.32,
    },
  },
];

export const DATA_SOURCES: DataSource[] = [
  {
    id: "1",
    name: "SEC EDGAR",
    status: "active",
    type: "api",
    itemsToday: 145,
    lastUpdate: "2 min ago",
  },
  {
    id: "2",
    name: "CourtListener",
    status: "active",
    type: "api",
    itemsToday: 32,
    lastUpdate: "5 min ago",
  },
  {
    id: "3",
    name: "Reuters Wire",
    status: "active",
    type: "rss",
    itemsToday: 89,
    lastUpdate: "1 min ago",
  },
  {
    id: "4",
    name: "Polymarket",
    status: "pending",
    type: "websocket",
    itemsToday: 12,
    lastUpdate: "15 min ago",
  },
  {
    id: "5",
    name: "Internal Watchlist",
    status: "error",
    type: "api",
    itemsToday: 0,
    lastUpdate: "4 hours ago",
  },
];

// M&A Deal Mock Data (Tasks 2.1-2.9)

export const MOCK_DEALS: Deal[] = [
  {
    id: "deal-1",
    symbol: "ATVI",
    acquirerSymbol: "MSFT",
    companyName: "Activision Blizzard",
    acquirerName: "Microsoft Corporation",
    announcementDate: "2022-01-18",
    acquisitionDate: "2024-06-30",
    outsideDate: "2024-07-18",
    reportedEquityTakeoverValue: 68700000000,
    considerationType: "CASH",
    p_close_base: 65,
    spread_entry_threshold: 2.5,
    currentSpread: 4.2,
    ev: 2.73,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: ["FTC_SECOND_REQUEST", "UK_CMA_REVIEW"],
    litigationCount: 3,
  },
  {
    id: "deal-2",
    symbol: "FIGM",
    acquirerSymbol: "ADBE",
    companyName: "Figma",
    acquirerName: "Adobe Inc.",
    announcementDate: "2022-09-15",
    acquisitionDate: "2024-03-31",
    outsideDate: "2024-05-15",
    reportedEquityTakeoverValue: 20000000000,
    considerationType: "MIXED",
    p_close_base: 15,
    spread_entry_threshold: 3.0,
    currentSpread: 8.5,
    ev: 1.28,
    status: "TERMINATED",
    regulatoryFlags: ["EU_REVIEW", "UK_CMA_REVIEW"],
    litigationCount: 0,
  },
  {
    id: "deal-3",
    symbol: "ACI",
    acquirerSymbol: "KR",
    companyName: "Albertsons Companies",
    acquirerName: "Kroger Co.",
    announcementDate: "2022-10-14",
    acquisitionDate: "2024-09-30",
    outsideDate: "2024-12-14",
    reportedEquityTakeoverValue: 24600000000,
    considerationType: "CASH",
    p_close_base: 35,
    spread_entry_threshold: 4.0,
    currentSpread: 6.8,
    ev: 2.38,
    status: "LITIGATION",
    regulatoryFlags: ["FTC_SECOND_REQUEST"],
    litigationCount: 5,
  },
  {
    id: "deal-4",
    symbol: "SAVE",
    acquirerSymbol: "JBLU",
    companyName: "Spirit Airlines",
    acquirerName: "JetBlue Airways",
    announcementDate: "2022-07-28",
    acquisitionDate: "2024-06-30",
    outsideDate: "2024-07-24",
    reportedEquityTakeoverValue: 3800000000,
    considerationType: "CASH",
    p_close_base: 25,
    spread_entry_threshold: 5.0,
    currentSpread: 12.3,
    ev: 3.08,
    status: "LITIGATION",
    regulatoryFlags: ["DOJ_INVESTIGATION"],
    litigationCount: 2,
  },
  {
    id: "deal-5",
    symbol: "TWTR",
    acquirerSymbol: "MUSK",
    companyName: "Twitter Inc.",
    acquirerName: "Elon Musk",
    announcementDate: "2022-04-25",
    acquisitionDate: "2022-10-27",
    outsideDate: "2022-10-28",
    reportedEquityTakeoverValue: 44000000000,
    considerationType: "CASH",
    p_close_base: 95,
    spread_entry_threshold: 1.0,
    currentSpread: 0.2,
    ev: 0.19,
    status: "CLOSED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-6",
    symbol: "VMW",
    acquirerSymbol: "AVGO",
    companyName: "VMware Inc.",
    acquirerName: "Broadcom Inc.",
    announcementDate: "2022-05-26",
    acquisitionDate: "2023-11-22",
    outsideDate: "2023-11-26",
    reportedEquityTakeoverValue: 61000000000,
    considerationType: "CASH",
    p_close_base: 98,
    spread_entry_threshold: 0.5,
    currentSpread: 0.3,
    ev: 0.29,
    status: "CLOSED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-7",
    symbol: "IRTC",
    acquirerSymbol: "BKNG",
    companyName: "iRobot Corporation",
    acquirerName: "Amazon.com Inc.",
    announcementDate: "2022-08-05",
    acquisitionDate: "2024-03-31",
    outsideDate: "2024-08-05",
    reportedEquityTakeoverValue: 1700000000,
    considerationType: "CASH",
    p_close_base: 40,
    spread_entry_threshold: 3.5,
    currentSpread: 5.2,
    ev: 2.08,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: ["EU_REVIEW"],
    litigationCount: 0,
  },
  {
    id: "deal-8",
    symbol: "SEAC",
    acquirerSymbol: "MSFT",
    companyName: "SeaChange International",
    acquirerName: "Accenture PLC",
    announcementDate: "2023-03-15",
    acquisitionDate: "2024-06-15",
    outsideDate: "2024-09-15",
    reportedEquityTakeoverValue: 850000000,
    considerationType: "CASH",
    p_close_base: 75,
    spread_entry_threshold: 2.0,
    currentSpread: 2.8,
    ev: 2.10,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-9",
    symbol: "HHR",
    acquirerSymbol: "WBD",
    companyName: "HeadHunter Group",
    acquirerName: "Sberbank",
    announcementDate: "2023-01-20",
    acquisitionDate: "2024-04-30",
    outsideDate: "2024-07-20",
    reportedEquityTakeoverValue: 1200000000,
    considerationType: "CASH",
    p_close_base: 55,
    spread_entry_threshold: 3.0,
    currentSpread: 4.5,
    ev: 2.48,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: [],
    litigationCount: 1,
  },
  {
    id: "deal-10",
    symbol: "CONE",
    acquirerSymbol: "T",
    companyName: "CyrusOne Inc.",
    acquirerName: "KKR & Global Infrastructure",
    announcementDate: "2021-11-15",
    acquisitionDate: "2022-04-01",
    outsideDate: "2022-05-15",
    reportedEquityTakeoverValue: 15000000000,
    considerationType: "CASH",
    p_close_base: 100,
    spread_entry_threshold: 0.5,
    currentSpread: 0.0,
    ev: 0.0,
    status: "CLOSED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-11",
    symbol: "CHTR",
    acquirerSymbol: "CMCSA",
    companyName: "Charter Communications",
    acquirerName: "Comcast Corporation",
    announcementDate: "2023-06-10",
    acquisitionDate: "2024-12-31",
    outsideDate: "2025-06-10",
    reportedEquityTakeoverValue: 95000000000,
    considerationType: "STOCK",
    p_close_base: 45,
    spread_entry_threshold: 4.0,
    currentSpread: 7.2,
    ev: 3.24,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-12",
    symbol: "ILMN",
    acquirerSymbol: "RHHBY",
    companyName: "Illumina Inc.",
    acquirerName: "Roche Holding AG",
    announcementDate: "2023-04-22",
    acquisitionDate: "2024-10-31",
    outsideDate: "2025-04-22",
    reportedEquityTakeoverValue: 42000000000,
    considerationType: "CASH",
    p_close_base: 60,
    spread_entry_threshold: 3.0,
    currentSpread: 5.8,
    ev: 3.48,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: ["FTC_SECOND_REQUEST", "EU_REVIEW"],
    litigationCount: 1,
  },
  {
    id: "deal-13",
    symbol: "PINS",
    acquirerSymbol: "GOOGL",
    companyName: "Pinterest Inc.",
    acquirerName: "Alphabet Inc.",
    announcementDate: "2023-08-15",
    acquisitionDate: "2024-12-31",
    outsideDate: "2025-02-15",
    reportedEquityTakeoverValue: 28000000000,
    considerationType: "STOCK",
    p_close_base: 52,
    spread_entry_threshold: 3.5,
    currentSpread: 6.2,
    ev: 3.22,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-14",
    symbol: "SNAP",
    acquirerSymbol: "META",
    companyName: "Snap Inc.",
    acquirerName: "Meta Platforms",
    announcementDate: "2023-09-01",
    acquisitionDate: "2024-11-30",
    outsideDate: "2025-03-01",
    reportedEquityTakeoverValue: 35000000000,
    considerationType: "MIXED",
    p_close_base: 38,
    spread_entry_threshold: 4.5,
    currentSpread: 8.9,
    ev: 3.38,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: ["FTC_SECOND_REQUEST"],
    litigationCount: 2,
  },
  {
    id: "deal-15",
    symbol: "DDOG",
    acquirerSymbol: "CSCO",
    companyName: "Datadog Inc.",
    acquirerName: "Cisco Systems",
    announcementDate: "2023-07-20",
    acquisitionDate: "2024-09-30",
    outsideDate: "2025-01-20",
    reportedEquityTakeoverValue: 18500000000,
    considerationType: "CASH",
    p_close_base: 68,
    spread_entry_threshold: 2.8,
    currentSpread: 3.9,
    ev: 2.65,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-16",
    symbol: "ZM",
    acquirerSymbol: "ORCL",
    companyName: "Zoom Video Communications",
    acquirerName: "Oracle Corporation",
    announcementDate: "2023-10-05",
    acquisitionDate: "2024-12-15",
    outsideDate: "2025-04-05",
    reportedEquityTakeoverValue: 22000000000,
    considerationType: "CASH",
    p_close_base: 72,
    spread_entry_threshold: 2.2,
    currentSpread: 3.1,
    ev: 2.23,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-17",
    symbol: "ROKU",
    acquirerSymbol: "NFLX",
    companyName: "Roku Inc.",
    acquirerName: "Netflix Inc.",
    announcementDate: "2023-11-12",
    acquisitionDate: "2025-01-31",
    outsideDate: "2025-05-12",
    reportedEquityTakeoverValue: 12000000000,
    considerationType: "STOCK",
    p_close_base: 58,
    spread_entry_threshold: 3.2,
    currentSpread: 5.4,
    ev: 3.13,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-18",
    symbol: "SPOT",
    acquirerSymbol: "AAPL",
    companyName: "Spotify Technology",
    acquirerName: "Apple Inc.",
    announcementDate: "2023-12-01",
    acquisitionDate: "2025-02-28",
    outsideDate: "2025-06-01",
    reportedEquityTakeoverValue: 45000000000,
    considerationType: "CASH",
    p_close_base: 42,
    spread_entry_threshold: 4.2,
    currentSpread: 7.8,
    ev: 3.28,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: ["EU_REVIEW"],
    litigationCount: 3,
  },
  {
    id: "deal-19",
    symbol: "DOCU",
    acquirerSymbol: "MSFT",
    companyName: "DocuSign Inc.",
    acquirerName: "Microsoft Corporation",
    announcementDate: "2023-05-18",
    acquisitionDate: "2024-08-31",
    outsideDate: "2024-11-18",
    reportedEquityTakeoverValue: 16000000000,
    considerationType: "CASH",
    p_close_base: 78,
    spread_entry_threshold: 1.8,
    currentSpread: 2.4,
    ev: 1.87,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-20",
    symbol: "TWLO",
    acquirerSymbol: "CRM",
    companyName: "Twilio Inc.",
    acquirerName: "Salesforce Inc.",
    announcementDate: "2023-06-25",
    acquisitionDate: "2024-10-15",
    outsideDate: "2024-12-25",
    reportedEquityTakeoverValue: 19000000000,
    considerationType: "STOCK",
    p_close_base: 64,
    spread_entry_threshold: 2.9,
    currentSpread: 4.3,
    ev: 2.75,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-21",
    symbol: "SQ",
    acquirerSymbol: "PYPL",
    companyName: "Block Inc.",
    acquirerName: "PayPal Holdings",
    announcementDate: "2023-08-30",
    acquisitionDate: "2024-11-30",
    outsideDate: "2025-02-28",
    reportedEquityTakeoverValue: 38000000000,
    considerationType: "MIXED",
    p_close_base: 48,
    spread_entry_threshold: 3.8,
    currentSpread: 6.7,
    ev: 3.22,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: ["FTC_SECOND_REQUEST"],
    litigationCount: 1,
  },
  {
    id: "deal-22",
    symbol: "SHOP",
    acquirerSymbol: "AMZN",
    companyName: "Shopify Inc.",
    acquirerName: "Amazon.com Inc.",
    announcementDate: "2023-09-15",
    acquisitionDate: "2025-01-15",
    outsideDate: "2025-03-15",
    reportedEquityTakeoverValue: 52000000000,
    considerationType: "CASH",
    p_close_base: 35,
    spread_entry_threshold: 4.8,
    currentSpread: 9.2,
    ev: 3.22,
    status: "LITIGATION",
    regulatoryFlags: ["FTC_SECOND_REQUEST", "EU_REVIEW"],
    litigationCount: 4,
  },
  {
    id: "deal-23",
    symbol: "UBER",
    acquirerSymbol: "GOOGL",
    companyName: "Uber Technologies",
    acquirerName: "Alphabet Inc.",
    announcementDate: "2023-10-20",
    acquisitionDate: "2025-02-28",
    outsideDate: "2025-04-20",
    reportedEquityTakeoverValue: 68000000000,
    considerationType: "STOCK",
    p_close_base: 28,
    spread_entry_threshold: 5.5,
    currentSpread: 11.3,
    ev: 3.16,
    status: "LITIGATION",
    regulatoryFlags: ["DOJ_INVESTIGATION", "EU_REVIEW"],
    litigationCount: 6,
  },
  {
    id: "deal-24",
    symbol: "LYFT",
    acquirerSymbol: "UBER",
    companyName: "Lyft Inc.",
    acquirerName: "Uber Technologies",
    announcementDate: "2023-11-08",
    acquisitionDate: "2025-03-31",
    outsideDate: "2025-05-08",
    reportedEquityTakeoverValue: 15000000000,
    considerationType: "STOCK",
    p_close_base: 22,
    spread_entry_threshold: 6.0,
    currentSpread: 13.5,
    ev: 2.97,
    status: "LITIGATION",
    regulatoryFlags: ["FTC_SECOND_REQUEST"],
    litigationCount: 5,
  },
  {
    id: "deal-25",
    symbol: "DASH",
    acquirerSymbol: "UBER",
    companyName: "DoorDash Inc.",
    acquirerName: "Uber Technologies",
    announcementDate: "2023-12-10",
    acquisitionDate: "2025-04-30",
    outsideDate: "2025-06-10",
    reportedEquityTakeoverValue: 32000000000,
    considerationType: "MIXED",
    p_close_base: 18,
    spread_entry_threshold: 7.0,
    currentSpread: 15.2,
    ev: 2.74,
    status: "LITIGATION",
    regulatoryFlags: ["FTC_SECOND_REQUEST", "DOJ_INVESTIGATION"],
    litigationCount: 7,
  },
  {
    id: "deal-26",
    symbol: "ABNB",
    acquirerSymbol: "BKNG",
    companyName: "Airbnb Inc.",
    acquirerName: "Booking Holdings",
    announcementDate: "2023-07-15",
    acquisitionDate: "2024-12-31",
    outsideDate: "2025-01-15",
    reportedEquityTakeoverValue: 78000000000,
    considerationType: "CASH",
    p_close_base: 55,
    spread_entry_threshold: 3.4,
    currentSpread: 5.9,
    ev: 3.25,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: ["EU_REVIEW"],
    litigationCount: 1,
  },
  {
    id: "deal-27",
    symbol: "COIN",
    acquirerSymbol: "ICE",
    companyName: "Coinbase Global",
    acquirerName: "Intercontinental Exchange",
    announcementDate: "2023-08-22",
    acquisitionDate: "2024-11-30",
    outsideDate: "2025-02-22",
    reportedEquityTakeoverValue: 24000000000,
    considerationType: "CASH",
    p_close_base: 62,
    spread_entry_threshold: 3.1,
    currentSpread: 4.8,
    ev: 2.98,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-28",
    symbol: "RBLX",
    acquirerSymbol: "MSFT",
    companyName: "Roblox Corporation",
    acquirerName: "Microsoft Corporation",
    announcementDate: "2023-09-28",
    acquisitionDate: "2025-01-31",
    outsideDate: "2025-03-28",
    reportedEquityTakeoverValue: 42000000000,
    considerationType: "STOCK",
    p_close_base: 70,
    spread_entry_threshold: 2.5,
    currentSpread: 3.7,
    ev: 2.59,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-29",
    symbol: "U",
    acquirerSymbol: "ORCL",
    companyName: "Unity Software",
    acquirerName: "Oracle Corporation",
    announcementDate: "2023-10-12",
    acquisitionDate: "2024-12-31",
    outsideDate: "2025-04-12",
    reportedEquityTakeoverValue: 14000000000,
    considerationType: "CASH",
    p_close_base: 66,
    spread_entry_threshold: 2.7,
    currentSpread: 4.1,
    ev: 2.71,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-30",
    symbol: "PLTR",
    acquirerSymbol: "MSFT",
    companyName: "Palantir Technologies",
    acquirerName: "Microsoft Corporation",
    announcementDate: "2023-11-20",
    acquisitionDate: "2025-02-28",
    outsideDate: "2025-05-20",
    reportedEquityTakeoverValue: 36000000000,
    considerationType: "CASH",
    p_close_base: 58,
    spread_entry_threshold: 3.3,
    currentSpread: 5.6,
    ev: 3.25,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-31",
    symbol: "SNOW",
    acquirerSymbol: "ORCL",
    companyName: "Snowflake Inc.",
    acquirerName: "Oracle Corporation",
    announcementDate: "2023-12-05",
    acquisitionDate: "2025-03-31",
    outsideDate: "2025-06-05",
    reportedEquityTakeoverValue: 48000000000,
    considerationType: "MIXED",
    p_close_base: 52,
    spread_entry_threshold: 3.6,
    currentSpread: 6.3,
    ev: 3.28,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-32",
    symbol: "CRWD",
    acquirerSymbol: "MSFT",
    companyName: "CrowdStrike Holdings",
    acquirerName: "Microsoft Corporation",
    announcementDate: "2023-06-18",
    acquisitionDate: "2024-09-30",
    outsideDate: "2024-12-18",
    reportedEquityTakeoverValue: 56000000000,
    considerationType: "CASH",
    p_close_base: 74,
    spread_entry_threshold: 2.1,
    currentSpread: 2.9,
    ev: 2.15,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-33",
    symbol: "ZS",
    acquirerSymbol: "CSCO",
    companyName: "Zscaler Inc.",
    acquirerName: "Cisco Systems",
    announcementDate: "2023-07-28",
    acquisitionDate: "2024-10-31",
    outsideDate: "2025-01-28",
    reportedEquityTakeoverValue: 28000000000,
    considerationType: "CASH",
    p_close_base: 68,
    spread_entry_threshold: 2.6,
    currentSpread: 3.8,
    ev: 2.58,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-34",
    symbol: "NET",
    acquirerSymbol: "GOOGL",
    companyName: "Cloudflare Inc.",
    acquirerName: "Alphabet Inc.",
    announcementDate: "2023-08-14",
    acquisitionDate: "2024-11-30",
    outsideDate: "2025-02-14",
    reportedEquityTakeoverValue: 32000000000,
    considerationType: "STOCK",
    p_close_base: 62,
    spread_entry_threshold: 3.0,
    currentSpread: 4.7,
    ev: 2.91,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-35",
    symbol: "OKTA",
    acquirerSymbol: "MSFT",
    companyName: "Okta Inc.",
    acquirerName: "Microsoft Corporation",
    announcementDate: "2023-09-22",
    acquisitionDate: "2024-12-31",
    outsideDate: "2025-03-22",
    reportedEquityTakeoverValue: 18000000000,
    considerationType: "CASH",
    p_close_base: 72,
    spread_entry_threshold: 2.3,
    currentSpread: 3.2,
    ev: 2.30,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-36",
    symbol: "MDB",
    acquirerSymbol: "ORCL",
    companyName: "MongoDB Inc.",
    acquirerName: "Oracle Corporation",
    announcementDate: "2023-10-30",
    acquisitionDate: "2025-01-31",
    outsideDate: "2025-04-30",
    reportedEquityTakeoverValue: 26000000000,
    considerationType: "CASH",
    p_close_base: 64,
    spread_entry_threshold: 2.9,
    currentSpread: 4.4,
    ev: 2.82,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-37",
    symbol: "DKNG",
    acquirerSymbol: "MGM",
    companyName: "DraftKings Inc.",
    acquirerName: "MGM Resorts",
    announcementDate: "2023-11-15",
    acquisitionDate: "2025-02-28",
    outsideDate: "2025-05-15",
    reportedEquityTakeoverValue: 22000000000,
    considerationType: "MIXED",
    p_close_base: 56,
    spread_entry_threshold: 3.4,
    currentSpread: 5.8,
    ev: 3.25,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: [],
    litigationCount: 1,
  },
  {
    id: "deal-38",
    symbol: "PENN",
    acquirerSymbol: "CZR",
    companyName: "PENN Entertainment",
    acquirerName: "Caesars Entertainment",
    announcementDate: "2023-12-08",
    acquisitionDate: "2025-03-31",
    outsideDate: "2025-06-08",
    reportedEquityTakeoverValue: 16000000000,
    considerationType: "STOCK",
    p_close_base: 60,
    spread_entry_threshold: 3.2,
    currentSpread: 5.3,
    ev: 3.18,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-39",
    symbol: "RIVN",
    acquirerSymbol: "TSLA",
    companyName: "Rivian Automotive",
    acquirerName: "Tesla Inc.",
    announcementDate: "2023-07-10",
    acquisitionDate: "2024-10-31",
    outsideDate: "2025-01-10",
    reportedEquityTakeoverValue: 34000000000,
    considerationType: "STOCK",
    p_close_base: 44,
    spread_entry_threshold: 4.2,
    currentSpread: 7.6,
    ev: 3.34,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: [],
    litigationCount: 2,
  },
  {
    id: "deal-40",
    symbol: "LCID",
    acquirerSymbol: "F",
    companyName: "Lucid Group",
    acquirerName: "Ford Motor Company",
    announcementDate: "2023-08-25",
    acquisitionDate: "2024-11-30",
    outsideDate: "2025-02-25",
    reportedEquityTakeoverValue: 12000000000,
    considerationType: "CASH",
    p_close_base: 50,
    spread_entry_threshold: 3.8,
    currentSpread: 6.9,
    ev: 3.45,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-41",
    symbol: "NKLA",
    acquirerSymbol: "GM",
    companyName: "Nikola Corporation",
    acquirerName: "General Motors",
    announcementDate: "2023-09-18",
    acquisitionDate: "2024-12-31",
    outsideDate: "2025-03-18",
    reportedEquityTakeoverValue: 8000000000,
    considerationType: "STOCK",
    p_close_base: 38,
    spread_entry_threshold: 4.8,
    currentSpread: 9.2,
    ev: 3.50,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-42",
    symbol: "BYND",
    acquirerSymbol: "TSN",
    companyName: "Beyond Meat",
    acquirerName: "Tyson Foods",
    announcementDate: "2023-10-25",
    acquisitionDate: "2025-01-31",
    outsideDate: "2025-04-25",
    reportedEquityTakeoverValue: 4500000000,
    considerationType: "CASH",
    p_close_base: 48,
    spread_entry_threshold: 4.0,
    currentSpread: 7.3,
    ev: 3.50,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-43",
    symbol: "OUST",
    acquirerSymbol: "NVDA",
    companyName: "Ouster Inc.",
    acquirerName: "NVIDIA Corporation",
    announcementDate: "2023-11-28",
    acquisitionDate: "2025-02-28",
    outsideDate: "2025-05-28",
    reportedEquityTakeoverValue: 6500000000,
    considerationType: "CASH",
    p_close_base: 70,
    spread_entry_threshold: 2.4,
    currentSpread: 3.5,
    ev: 2.45,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-44",
    symbol: "LAZR",
    acquirerSymbol: "INTC",
    companyName: "Luminar Technologies",
    acquirerName: "Intel Corporation",
    announcementDate: "2023-12-12",
    acquisitionDate: "2025-03-31",
    outsideDate: "2025-06-12",
    reportedEquityTakeoverValue: 5800000000,
    considerationType: "CASH",
    p_close_base: 66,
    spread_entry_threshold: 2.7,
    currentSpread: 4.0,
    ev: 2.64,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-45",
    symbol: "AFRM",
    acquirerSymbol: "PYPL",
    companyName: "Affirm Holdings",
    acquirerName: "PayPal Holdings",
    announcementDate: "2023-06-30",
    acquisitionDate: "2024-09-30",
    outsideDate: "2024-12-30",
    reportedEquityTakeoverValue: 14000000000,
    considerationType: "MIXED",
    p_close_base: 58,
    spread_entry_threshold: 3.3,
    currentSpread: 5.7,
    ev: 3.31,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-46",
    symbol: "UPST",
    acquirerSymbol: "GS",
    companyName: "Upstart Holdings",
    acquirerName: "Goldman Sachs",
    announcementDate: "2023-07-22",
    acquisitionDate: "2024-10-31",
    outsideDate: "2025-01-22",
    reportedEquityTakeoverValue: 9500000000,
    considerationType: "CASH",
    p_close_base: 54,
    spread_entry_threshold: 3.5,
    currentSpread: 6.2,
    ev: 3.35,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-47",
    symbol: "SOFI",
    acquirerSymbol: "JPM",
    companyName: "SoFi Technologies",
    acquirerName: "JPMorgan Chase",
    announcementDate: "2023-08-16",
    acquisitionDate: "2024-11-30",
    outsideDate: "2025-02-16",
    reportedEquityTakeoverValue: 18000000000,
    considerationType: "CASH",
    p_close_base: 62,
    spread_entry_threshold: 3.0,
    currentSpread: 4.8,
    ev: 2.98,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-48",
    symbol: "HOOD",
    acquirerSymbol: "SCHW",
    companyName: "Robinhood Markets",
    acquirerName: "Charles Schwab",
    announcementDate: "2023-09-20",
    acquisitionDate: "2024-12-31",
    outsideDate: "2025-03-20",
    reportedEquityTakeoverValue: 16000000000,
    considerationType: "STOCK",
    p_close_base: 56,
    spread_entry_threshold: 3.4,
    currentSpread: 5.9,
    ev: 3.30,
    status: "REGULATORY_REVIEW",
    regulatoryFlags: [],
    litigationCount: 1,
  },
  {
    id: "deal-49",
    symbol: "OPEN",
    acquirerSymbol: "Z",
    companyName: "Opendoor Technologies",
    acquirerName: "Zillow Group",
    announcementDate: "2023-10-28",
    acquisitionDate: "2025-01-31",
    outsideDate: "2025-04-28",
    reportedEquityTakeoverValue: 7200000000,
    considerationType: "STOCK",
    p_close_base: 52,
    spread_entry_threshold: 3.6,
    currentSpread: 6.4,
    ev: 3.33,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-50",
    symbol: "RDFN",
    acquirerSymbol: "COMP",
    companyName: "Redfin Corporation",
    acquirerName: "Compass Inc.",
    announcementDate: "2023-11-22",
    acquisitionDate: "2025-02-28",
    outsideDate: "2025-05-22",
    reportedEquityTakeoverValue: 5400000000,
    considerationType: "MIXED",
    p_close_base: 48,
    spread_entry_threshold: 4.0,
    currentSpread: 7.5,
    ev: 3.60,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-51",
    symbol: "CVNA",
    acquirerSymbol: "KMX",
    companyName: "Carvana Co.",
    acquirerName: "CarMax Inc.",
    announcementDate: "2023-12-15",
    acquisitionDate: "2025-03-31",
    outsideDate: "2025-06-15",
    reportedEquityTakeoverValue: 11000000000,
    considerationType: "CASH",
    p_close_base: 42,
    spread_entry_threshold: 4.5,
    currentSpread: 8.3,
    ev: 3.49,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
  {
    id: "deal-52",
    symbol: "PTON",
    acquirerSymbol: "NKE",
    companyName: "Peloton Interactive",
    acquirerName: "Nike Inc.",
    announcementDate: "2023-06-28",
    acquisitionDate: "2024-09-30",
    outsideDate: "2024-12-28",
    reportedEquityTakeoverValue: 9800000000,
    considerationType: "CASH",
    p_close_base: 60,
    spread_entry_threshold: 3.2,
    currentSpread: 5.4,
    ev: 3.24,
    status: "ANNOUNCED",
    regulatoryFlags: [],
    litigationCount: 0,
  },
];

// Mock Events (Task 2.3) - Varying materiality across all event types
export const MOCK_EVENTS: Event[] = [
  // MSFT/ATVI events
  {
    id: "event-1",
    dealId: "deal-1",
    timestamp: "2023-12-08T14:32:00Z",
    type: "AGENCY",
    subtype: "FTC Second Request",
    materiality: "HIGH",
    title: "FTC Issues Second Request Under HSR Act",
    summary: "FTC has issued a Second Request for additional information, extending the review period by 30 days. This indicates deeper scrutiny of potential competitive concerns in the gaming market.",
    sourceUrl: "https://www.ftc.gov/news-events/press-releases/2023/12/ftc-issues-second-request-microsoft-activision",
    sourceType: "FTC_GOV",
  },
  {
    id: "event-2",
    dealId: "deal-1",
    timestamp: "2023-11-15T09:20:00Z",
    type: "COURT",
    subtype: "Preliminary Injunction Denied",
    materiality: "HIGH",
    title: "Court Denies FTC's Motion for Preliminary Injunction",
    summary: "U.S. District Court denied FTC's request to block the merger, finding insufficient evidence of likely competitive harm. FTC may appeal.",
    sourceUrl: "https://courtlistener.com/docket/67890/ftc-v-microsoft",
    sourceType: "COURT_LISTENER",
  },
  {
    id: "event-3",
    dealId: "deal-1",
    timestamp: "2023-10-22T16:45:00Z",
    type: "FILING",
    subtype: "8-K Amendment",
    materiality: "MEDIUM",
    title: "8-K Amendment: Outside Date Extended",
    summary: "Parties have agreed to extend the outside date from June 30, 2024 to July 18, 2024 to allow additional time for regulatory approvals.",
    sourceUrl: "https://www.sec.gov/edgar/browse/?CIK=0000789019",
    sourceType: "SEC_EDGAR",
  },
  {
    id: "event-4",
    dealId: "deal-1",
    timestamp: "2023-12-10T11:00:00Z",
    type: "SPREAD_MOVE",
    subtype: "Spread Widening",
    materiality: "MEDIUM",
    title: "Spread Widens to 4.2% (+0.8%)",
    summary: "Deal spread widened from 3.4% to 4.2% following FTC Second Request announcement, reflecting increased regulatory risk.",
    sourceUrl: "",
    sourceType: "SEC_EDGAR",
  },
  {
    id: "event-5",
    dealId: "deal-1",
    timestamp: "2023-11-28T08:15:00Z",
    type: "NEWS",
    subtype: "Analyst Note",
    materiality: "LOW",
    title: "Wachtell: Microsoft Commitments May Address FTC Concerns",
    summary: "Wachtell Lipton analysis suggests Microsoft's 10-year Call of Duty commitments to Sony and Nintendo could mitigate FTC's foreclosure theory.",
    sourceUrl: "https://www.wlrk.com/insights/microsoft-activision-analysis",
    sourceType: "RSS",
  },
  // Adobe/Figma events (terminated deal)
  {
    id: "event-6",
    dealId: "deal-2",
    timestamp: "2023-12-17T10:00:00Z",
    type: "AGENCY",
    subtype: "Deal Termination",
    materiality: "HIGH",
    title: "Adobe and Figma Mutually Terminate Merger Agreement",
    summary: "Parties have mutually agreed to terminate the merger due to no clear path to regulatory approval in EU and UK. Adobe will pay $1B reverse termination fee.",
    sourceUrl: "https://news.adobe.com/news/2023/12/adobe-figma-termination",
    sourceType: "RSS",
  },
  {
    id: "event-7",
    dealId: "deal-2",
    timestamp: "2023-11-30T14:20:00Z",
    type: "AGENCY",
    subtype: "UK CMA Provisional Findings",
    materiality: "HIGH",
    title: "UK CMA Issues Provisional Findings Against Merger",
    summary: "CMA found the merger would substantially lessen competition in product design software markets and is minded to prohibit the transaction.",
    sourceUrl: "https://www.gov.uk/cma-cases/adobe-figma-merger-inquiry",
    sourceType: "RSS",
  },
  // Kroger/Albertsons events (litigation)
  {
    id: "event-8",
    dealId: "deal-3",
    timestamp: "2023-12-05T13:45:00Z",
    type: "COURT",
    subtype: "State AG Lawsuit Filed",
    materiality: "HIGH",
    title: "Washington and Colorado AGs File Suit to Block Merger",
    summary: "State attorneys general filed lawsuit alleging merger would reduce competition and harm consumers through higher prices and reduced quality.",
    sourceUrl: "https://courtlistener.com/docket/78901/washington-v-kroger",
    sourceType: "COURT_LISTENER",
  },
  {
    id: "event-9",
    dealId: "deal-3",
    timestamp: "2023-11-18T09:30:00Z",
    type: "FILING",
    subtype: "S-4 Amendment",
    materiality: "MEDIUM",
    title: "S-4 Amendment: Divestiture Plan Updated",
    summary: "Updated divestiture plan to sell 413 stores (up from 400) to C&S Wholesale Grocers to address FTC competitive concerns.",
    sourceUrl: "https://www.sec.gov/edgar/browse/?CIK=0000056873",
    sourceType: "SEC_EDGAR",
  },
  // JetBlue/Spirit events
  {
    id: "event-10",
    dealId: "deal-4",
    timestamp: "2023-12-12T15:00:00Z",
    type: "COURT",
    subtype: "DOJ Trial Begins",
    materiality: "HIGH",
    title: "DOJ Antitrust Trial Begins in Boston",
    summary: "Trial commenced with DOJ arguing merger would eliminate Spirit's low-cost business model and harm price-sensitive consumers.",
    sourceUrl: "https://courtlistener.com/docket/89012/doj-v-jetblue",
    sourceType: "COURT_LISTENER",
  },
  // Illumina/Roche events
  {
    id: "event-11",
    dealId: "deal-12",
    timestamp: "2023-12-01T10:30:00Z",
    type: "AGENCY",
    subtype: "EU Phase II Investigation",
    materiality: "HIGH",
    title: "European Commission Opens In-Depth Investigation",
    summary: "EC has concerns that the merger may reduce competition in genomic sequencing markets and has opened a Phase II investigation.",
    sourceUrl: "https://ec.europa.eu/commission/presscorner/detail/en/IP_23_6543",
    sourceType: "RSS",
  },
];

// Mock Clauses (Task 2.4) - Extracted from SEC filings
export const MOCK_CLAUSES: Clause[] = [
  {
    id: "clause-1",
    dealId: "deal-1",
    type: "TERMINATION_FEE",
    value: "$3.0 billion",
    sourceFilingType: "S-4",
    sourceSection: "Section 7.2(b)",
    sourceUrl: "https://www.sec.gov/edgar/browse/?CIK=0000789019",
  },
  {
    id: "clause-2",
    dealId: "deal-1",
    type: "REVERSE_TERMINATION_FEE",
    value: "$3.0 billion",
    sourceFilingType: "S-4",
    sourceSection: "Section 7.2(c)",
    sourceUrl: "https://www.sec.gov/edgar/browse/?CIK=0000789019",
  },
  {
    id: "clause-3",
    dealId: "deal-1",
    type: "MAE",
    value: "Standard with carve-outs for regulatory changes and pandemic effects",
    sourceFilingType: "S-4",
    sourceSection: "Section 8.3",
    sourceUrl: "https://www.sec.gov/edgar/browse/?CIK=0000789019",
  },
  {
    id: "clause-4",
    dealId: "deal-1",
    type: "REGULATORY_EFFORTS",
    value: "Reasonable best efforts; Microsoft to divest if required",
    sourceFilingType: "S-4",
    sourceSection: "Section 5.7",
    sourceUrl: "https://www.sec.gov/edgar/browse/?CIK=0000789019",
  },
  {
    id: "clause-5",
    dealId: "deal-2",
    type: "TERMINATION_FEE",
    value: "$400 million",
    sourceFilingType: "DEFM14A",
    sourceSection: "Section 7.2(b)",
    sourceUrl: "https://www.sec.gov/edgar/browse/?CIK=0000796343",
  },
  {
    id: "clause-6",
    dealId: "deal-2",
    type: "REVERSE_TERMINATION_FEE",
    value: "$1.0 billion",
    sourceFilingType: "DEFM14A",
    sourceSection: "Section 7.2(c)",
    sourceUrl: "https://www.sec.gov/edgar/browse/?CIK=0000796343",
  },
  {
    id: "clause-7",
    dealId: "deal-3",
    type: "TERMINATION_FEE",
    value: "$600 million",
    sourceFilingType: "S-4",
    sourceSection: "Section 7.2(b)",
    sourceUrl: "https://www.sec.gov/edgar/browse/?CIK=0000056873",
  },
  {
    id: "clause-8",
    dealId: "deal-3",
    type: "REGULATORY_EFFORTS",
    value: "Reasonable best efforts; divestiture of up to 650 stores if required",
    sourceFilingType: "S-4",
    sourceSection: "Section 5.7",
    sourceUrl: "https://www.sec.gov/edgar/browse/?CIK=0000056873",
  },
];

// Mock Market Snapshots (Task 2.5) - 6 months of daily data for deal-1
export const MOCK_MARKET_SNAPSHOTS: MarketSnapshot[] = Array.from({ length: 180 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (180 - i));
  const baseSpread = 3.5;
  const volatility = 0.8;
  const trend = i < 60 ? -0.2 : i < 120 ? 0.3 : 0.5;
  const spread = baseSpread + trend + (Math.random() - 0.5) * volatility;

  return {
    dealId: "deal-1",
    timestamp: date.toISOString(),
    targetPrice: 95.00 + spread,
    acquirerPrice: 380.50,
    offerPrice: 95.00,
    spread: Math.max(0, spread),
    volume: Math.floor(Math.random() * 5000000) + 1000000,
  };
});

// Mock News Items (Task 2.6)
export const MOCK_NEWS: NewsItem[] = [
  {
    id: "news-1",
    dealId: "deal-1",
    timestamp: "2023-12-15T14:30:00Z",
    source: "Skadden Arps M&A Alert",
    title: "Gaming Industry Consolidation: Regulatory Trends",
    summary: "Analysis of recent FTC enforcement actions in technology mergers, with focus on vertical integration theories and behavioral remedies.",
    url: "https://www.skadden.com/insights/publications/2023/12/gaming-consolidation",
    tags: ["Antitrust", "Gaming", "FTC"],
  },
  {
    id: "news-2",
    dealId: "deal-1",
    timestamp: "2023-12-10T09:15:00Z",
    source: "Wachtell Lipton",
    title: "Microsoft's Commitments May Satisfy Regulators",
    summary: "Legal analysis suggests 10-year licensing commitments to competitors could address foreclosure concerns raised by FTC and CMA.",
    url: "https://www.wlrk.com/insights/microsoft-commitments-analysis",
    tags: ["Remedies", "Licensing"],
  },
  {
    id: "news-3",
    dealId: "deal-2",
    timestamp: "2023-12-17T11:00:00Z",
    source: "Bloomberg Law",
    title: "Adobe Pays $1B Breakup Fee as Figma Deal Collapses",
    summary: "Merger termination marks rare instance of reverse termination fee payment and highlights increasing regulatory skepticism of tech acquisitions.",
    url: "https://news.bloomberglaw.com/mergers-and-acquisitions/adobe-figma-termination",
    tags: ["Termination", "Tech M&A"],
  },
  {
    id: "news-4",
    dealId: "deal-3",
    timestamp: "2023-12-08T16:45:00Z",
    source: "Cravath Client Memo",
    title: "Grocery Merger Litigation: State AG Coordination",
    summary: "Multi-state AG coordination in merger challenges represents new enforcement trend, with implications for deal timing and divestiture negotiations.",
    url: "https://www.cravath.com/insights/grocery-merger-state-ags",
    tags: ["State AGs", "Retail"],
  },
];
